def main_menu():
    player.display_status()
    print(f"\nWhat do you want to do, {player.name}?\n")
    time.sleep(1)
    next_action = 0
    try:
        # This is the actual main_menu being displayed, making the player choose an option at the same time.
        time.sleep(0.3)
        print(f"  0: {player.name}")
        time.sleep(0.3)
        print(f"  1: gather wood")
        time.sleep(0.3)
        print(f"  2: forage")
        time.sleep(0.3)
        print(f"  3: hunt")
        time.sleep(0.3)
        print(f"  4: craft")
        time.sleep(0.3)
        print(f"  5: rest")
        time.sleep(0.3)
        print(f"  6: sleep")
        time.sleep(0.3)
        print(f"  7: explore")
        time.sleep(0.3)
        print(f" 10: info")
        time.sleep(0.3)
        print(f" 23: {color.RED}Exit{color.END}\n  ")
        time.sleep(0.3)